version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.3
    - 2.7.4
    - 2.8.2
  - dependency-name: ipython
    versions:
    - 7.20.0
    - 7.22.0
  - dependency-name: pycodestyle
    versions:
    - 2.7.0
