language: python
python: 3.5

addons:
  apt:
    packages:
      - colordiff
install:
  - pip install ansible==2.4
  - pip install --requirement requirements.txt
  - pip install enum34
  - pip install pathlib
  - pip install typing
script:
  - ./test.sh
  - vint .vimrc*
  - yamllint .
