language: python
python: 2.7

addons:
  apt:
    packages:
      - colordiff
install:
  - pip install ansible
  - pip install --requirement requirements.txt
  - pip install enum34
  - pip install pathlib
  - pip install typing
script:
  - ./test.sh
  - vint .vimrc*
  - yamllint .
