dist: xenial
language: python
python:
  - 3.7

addons:
  apt:
    packages:
      - colordiff
install:
  - pip install --requirement requirements.txt
  - pip install ansible
  - pip install enum34
  - pip install pathlib
  - pip install typing
script:
  - vint .vimrc*
  - yamllint .
  - ./test.sh
