dist: focal

addons:
  apt:
    packages:
      - colordiff
install:
  - pip install --requirement requirements.txt
  - pip install ansible
  - pip install enum34
  - pip install pathlib
  - pip install typing
script:
  - vint dotfiles_shared/.vimrc*
  - yamllint --config-file dotfiles_shared/.config/yamllint/config.symlink .
  - ./run_tests.sh
