---
- hosts: localhost
  connection: local
  vars:
    home_directory: "{{ lookup('env', 'HOME') }}"
  tasks:

    - name: Find files to symlink
      find:
        patterns:  "*.symlink"
        paths: "{{ playbook_dir }}"
        recurse: yes
        file_type: any
        hidden: yes
      register: files_to_symlink
    - name: Ensure directories for symlinks
      file:
        path: "{{ home_directory }}/{{ item.path.replace(playbook_dir, '').replace('.symlink', '').rsplit('/', 1)[0] }}"
        state: directory
      with_items: "{{ files_to_symlink.files }}"
    - name: Create symlinks
      file:
        src: "{{ item.path }}"
        dest: "{{ home_directory }}/{{ item.path.replace(playbook_dir, '').replace('.symlink', '') }}"
        state: link
      with_items: "{{ files_to_symlink.files }}"

    - name: Install Tmux plugin manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ home_directory }}/.tmux/plugins/tpm"
        update: no

    - name: Install Vim plugin manager
      git:
        repo: https://github.com/gmarik/Vundle.vim.git
        dest: "{{ home_directory }}/.vim/bundle/vundle"
        update: no

    - name: Install ZSH syntax highlighting plugin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: "{{ home_directory }}/.zsh/plugins/zsh-syntax-highlighting"
        update: no

    - name: Install ZSH git prompt plugin
      git:
        repo: https://github.com/olivierverdier/zsh-git-prompt
        dest: "{{ home_directory }}/.zsh/plugins/zsh-git-prompt"
        update: no
      register: git_prompt_plugin
    - name: Fix naming in ZSH git prompt plugin
      copy:
        src: "{{ home_directory }}/.zsh/plugins/zsh-git-prompt/zshrc.sh"
        dest: "{{ home_directory }}/.zsh/plugins/zsh-git-prompt/zsh-git-prompt.plugin.zsh"
      when: git_prompt_plugin.changed

    - name: Install ZSH pip plugin
      get_url:
        url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/plugins/pip/pip.plugin.zsh
        dest: "{{ home_directory }}/.zsh/plugins/"

    - name: Ensure directory for ZSH completions
      file:
        path: "{{ home_directory }}/.zsh/completions.d/"
        state: directory
    - name: Install ZSH completions
      get_url:
        url: "{{ item }}"
        dest: "{{ home_directory }}/.zsh/completions.d/{{ item.split('/')[-1] }}"
      with_items:
        - https://raw.githubusercontent.com/ggreer/the_silver_searcher/master/_the_silver_searcher
        - https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/plugins/gem/_gem
        - https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/plugins/pip/_pip
        - https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_ansible
        - https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_ansible-playbook
        - https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_httpie
        - https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_jq
        - https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_rvm
        - https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_sbt
        - https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_scala
        - https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_setup.py
        - https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_vagrant
        - https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_virtualbox

    - name: Ensure directory for BASH completions
      file:
        path: "{{ home_directory }}/.zsh/bash_completions.d/"
        state: directory
    - name: Install limes completion
      get_url:
        url: https://raw.githubusercontent.com/otm/limes/master/assets/limes
        dest: "{{ home_directory }}/.zsh/bash_completions.d/limes"
      register: limes
    - name: Patch limes completion
      patch:
        src: "{{ playbook_dir }}/patches/limes"
        dest: "{{ limes.dest }}"
      when: limes.changed
