---
- hosts: localhost
  connection: local
  vars:
    home_directory: "{{ lookup('env', 'HOME') }}"
  tasks:

    - name: Find files to symlink
      find:
        patterns:  "*.symlink"
        paths: "{{ playbook_dir }}"
        recurse: yes
        file_type: any
      register: files_to_symlink
    - name: Ensure directories for symlinks
      file:
        path: "{{ home_directory }}/{{ item.path.replace(playbook_dir, '').replace('.symlink', '').rsplit('/', 1)[0] }}"
        state: directory
      with_items: "{{ files_to_symlink.files }}"
    - name: Create symlinks
      file:
        src: "{{ item.path }}"
        dest: "{{ home_directory }}/{{ item.path.replace(playbook_dir, '').replace('.symlink', '') }}"
        state: link
      with_items: "{{ files_to_symlink.files }}"

    - name: Clone Tmux plugin manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ home_directory }}/.tmux/plugins/tpm"
        update: no

    - name: Clone Vim plugin manager
      git:
        repo: https://github.com/gmarik/Vundle.vim.git
        dest: "{{ home_directory }}/.vim/bundle/vundle"
        update: no
