- name: "Python package {{ package.key }}: Create virtualenv"
  shell: |
    python3.11 -m venv {{ target_directory }}/.opt/{{ package.key }}
  args:
    creates: "{{ target_directory }}/.opt/{{ package.key }}"
    executable: /bin/bash
  environment:
    PATH: |
      {%- if "VIRTUAL_ENV" in ansible_env -%}
        {{ target_directory }}/.bin:{{ target_directory }}/.asdf/shims:{{ ansible_env.PATH | replace(ansible_env.VIRTUAL_ENV + "/bin:", "") }}
      {%- else -%}
        {{ target_directory }}/.bin:{{ target_directory }}/.asdf/shims:{{ ansible_env.PATH }}
      {%- endif -%}
  register: virtual_env_creation

- name: "Python package {{ package.key }}: Install essential requirements"
  command: |
    {{ target_directory }}/.opt/{{ package.key }}/bin/python -m pip install --requirement {{ playbook_dir }}/../requirements-essential.txt
  register: essential_requirements_install
  changed_when: essential_requirements_install.stdout_lines[-1] is match("Successfully installed .*")

- name: "Python package {{ package.key }}: Install requirements"
  command: |
    {{ target_directory }}/.opt/{{ package.key }}/bin/pip install --requirement {{ playbook_dir }}/includes/requirements-{{ package.key }}.txt
  register: requirements_install
  changed_when: requirements_install.stdout_lines[-1] is match("Successfully installed .*")

- name: "Python package {{ package.key }}: Add link in .bin"
  file:
    dest: "{{ target_directory }}/.bin/{{ item.key }}"
    src: "{{ target_directory }}/.opt/{{ package.key }}/bin/{{ item.value }}"
    state: link
    mode: 0755
  loop: "{{ package.value.links | default({package.key: package.key}) | dict2items }}"
