- name: "Python package {{ package.key }}: Create virtualenv"
  shell: |
    source {{ target_directory }}/.asdf/asdf.sh
    python3.9 -m venv {{ target_directory }}/.opt/{{ package.key }}
  args:
    chdir: "{{ target_directory }}"  # make sure asdf config is picked up
    creates: "{{ target_directory }}/.opt/{{ package.key }}"
    executable: /bin/bash
  environment:
    PATH: |
      {%- if "VIRTUAL_ENV" in ansible_env -%}
        {{ ansible_env.PATH | replace(ansible_env.VIRTUAL_ENV + "/bin:", "") }}
      {%- else -%}
        {{ ansible_env.PATH }}
      {%- endif -%}
  register: virtual_env_creation

- name: "Python package {{ package.key }}: Check essential requirements"
  command: |
    {{ target_directory }}/.opt/{{ package.key }}/bin/python -c "import pkg_resources; pkg_resources.require(open('{{ playbook_dir }}/../requirements-essential.txt'))"
  changed_when: false
  failed_when: false
  register: essential_requirements_check

- name: "Python package {{ package.key }}: Install essential requirements"
  command: |
    {{ target_directory }}/.opt/{{ package.key }}/bin/python -m pip install --requirement {{ playbook_dir }}/../requirements-essential.txt
  when: essential_requirements_check.rc != 0
  changed_when: true

- name: "Python package {{ package.key }}: Check requirements"
  command: |
    {{ target_directory }}/.opt/{{ package.key }}/bin/python -c "import pkg_resources; pkg_resources.require(open('{{ playbook_dir }}/includes/requirements-{{ package.key }}.txt'))"
  changed_when: false
  failed_when: false
  register: requirements_check

- name: "Python package {{ package.key }}: Install requirements"
  command: |
    {{ target_directory }}/.opt/{{ package.key }}/bin/pip install --requirement {{ playbook_dir }}/includes/requirements-{{ package.key }}.txt
  when: not (virtual_env_creation.stdout | regex_search("skipped")) or requirements_check.stderr | regex_search("pkg_resources.DistributionNotFound|pkg_resources.VersionConflict")
  changed_when: true

- name: "Python package {{ package.key }}: Add link in .bin"
  file:
    dest: "{{ target_directory }}/.bin/{{ item.key }}"
    src: "{{ target_directory }}/.opt/{{ package.key }}/bin/{{ item.value }}"
    state: link
    mode: 0755
  loop: "{{ package.value.links | default({package.key: package.key}) | dict2items }}"
