- name: Check for {{ product | title }}
  stat:
    path: "{{ target_directory }}/.bin/{{ product }}_{{ version | regex_replace('\\.', '_')  }}"
  register: stat_result
- name: Add {{ product | title }}
  block:

    - name: Download {{ product | title }}
      get_url:
        url: "{{ url }}"
        dest: /tmp/{{ product }}{{ version }}.zip
      register: download
    - name: Unpack {{ product | title }}
      unarchive:
        src: "{{ download.dest }}"
        dest: /tmp/
        remote_src: true
    - name: Copy {{ product | title }}
      copy:
        src: /tmp/{{ zipped_binary_path | default(product) }}
        dest: "{{ target_directory }}/.bin/{{ product }}_{{ version | regex_replace('\\.', '_') }}"
        mode: 0755
        remote_src: true

  when: not stat_result.stat.exists

- name: Link {{ product | title }}
  file:
    src: "{{ target_directory }}/.bin/{{ product }}_{{ version | regex_replace('\\.', '_') }}"
    dest: "{{ target_directory }}/.bin/{{ product }}"
    state: link

# vim: syntax=ansible
