#!/usr/bin/env python3

import subprocess
import sys

GIT_MESSAGE_DELIMITER = "# ------------------------ >8 ------------------------"
NUMBER_OF_COMMITS = 5
LAST_COMMITS_HEADER = f"Last {NUMBER_OF_COMMITS} commits:"


def main():
    # git commit called with additional arguments
    if sys.argv[2:]:
        return

    commit_message_filepath = sys.argv[1]
    result = subprocess.run(
        [
            "git",
            "log",
            "-n",
            str(NUMBER_OF_COMMITS),
            "--pretty=format:%h: %s%d",
            "--abbrev-commit",
            '--date=format-local:"%F %T %z"',
        ],
        stdout=subprocess.PIPE,
        text=True,
        check=True,
    )
    commits = result.stdout.strip().split("\n")

    with open(commit_message_filepath, "r", encoding="utf-8") as in_file:
        lines = in_file.readlines()

    with open(commit_message_filepath, "w", encoding="utf-8") as out_file:
        for line in lines:
            if line.strip() == GIT_MESSAGE_DELIMITER:
                out_file.write(f"# {LAST_COMMITS_HEADER}\n")
                for commit in commits:
                    out_file.write(f"#   {commit}\n")
                out_file.write("#\n")
            out_file.write(line)


if __name__ == "__main__":
    main()
