GIT_LOG_FORMAT='%C(blue)%h%Creset -%C(yellow)%d%Creset %s %C(blue)(%ai) %C(bold blue)<%an (%ae)>%Creset'
alias glog='git log --graph --decorate --pretty=format:$GIT_LOG_FORMAT --abbrev-commit --date=short --abbrev=8'

alias ga='git add'
alias gap='git add --patch'
alias gash='git stash --include-untracked --keep-index'
alias gashl='git stash list'
alias gashp='git stash pop'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff --color=always'
alias gdc='git diff --color=always --cached'
alias gdt='git difftool'
alias gdtc='git difftool --cached'
alias gf='git fetch'
alias gl='glog'
alias gla='glog --all'
alias gld='glog --left-right --graph --cherry-mark'
alias gldo='glog --left-right --graph'
alias gm='git merge'
alias gmd='git merge --ff-only origin/develop'
alias gmm='git merge --ff-only origin/master'
alias gps='git push'
alias grb='git rebase'
