alias -g C="| wc --lines"
alias -g H="| head --lines 25"
alias -g I="|  add-index --input-type list  --print-indexables | set-index-variables"
alias -g IF="| add-index --input-type mixed --print-indexables | set-index-variables"
alias -g T="| tail --lines 25"
