#!/bin/bash

FIRST_SERVER=$1

SERVERS="$@"
SERVER_COUNT=$#

if [ "$SERVER_COUNT" == "1" ]; then
  COMMAND=ssh
  WINDOW_NAME="${COMMAND}_$SERVERS"
else
  COMMAND=cssh
  WINDOW_NAME="${COMMAND}_$(echo $SERVERS | awk '{split($FIRST_SERVER,a,"-"); printf "%s_%s", a[1], a[2]}')"
fi


if [[ -z "$TMUX" ]]; then
  if tmux has-session; then
    tmux new-window
  else
    tmux new-session -d
  fi
else
  tmux new-window
fi

tmux rename-window $WINDOW_NAME

for SERVER in $SERVERS; do
  tmux split-window "ssh $SERVER"
  tmux select-layout tiled
done
tmux kill-pane -t 0
tmux select-pane -t 0
tmux select-layout tiled
tmux set-window-option synchronize-panes on

