#!/bin/bash

SERVERS="$@"
SESSION_NAME="ssh_$(echo $SERVERS | awk '{split($0,a,"-"); printf "%s_%s", a[1], a[2]}')"

tmux new-session -d -s $SESSION_NAME

shift
for SERVER in $SERVERS; do
  tmux split-window "ssh $SERVER"
  tmux select-layout tiled
done
tmux kill-pane -t 0
tmux select-pane -t 0
tmux select-layout tiled
tmux set-window-option synchronize-panes on
tmux -2 attach -t $SESSION_NAME

