- name: Utils
  import_playbook: utils.yml
  vars:
    architecture: amd64
    os: darwin
    tar: /opt/homebrew/bin/gtar
- name: ASDF
  import_playbook: asdf.yml
- name: Brew
  import_playbook: brew.yml
- name: Completions
  import_playbook: completions.yml
- name: Shared dotfiles
  import_playbook: dotfiles.yml
  vars:
    dotfiles_directory: dotfiles_shared
- name: Plugins
  import_playbook: plugins.yml
- name: Node utils
  import_playbook: utils-npm.yml
- name: Python utils
  import_playbook: utils-python.yml
- name: Rust utils
  import_playbook: utils-rust.yml
