- name: Play to install Brew packages
  hosts: all

  tasks:

    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
      loop:
        - bash
        - bat
        - colima
        - colordiff
        - coreutils
        - docker  # this is the docker cli (https://github.com/docker/cli), not docker desktop
        - docker-buildx
        - docker-compose
        - docker-credential-helper-ecr
        - entr
        - fd
        - gnu-sed
        - gnu-tar
        - gpg
        - grep
        - htop
        - jo
        - jq
        - moreutils
        - neovim
        - oath-toolkit
        - pv
        - rename
        - ripgrep
        - shellcheck
        - tmux
        - tree

    - name: Install homebrew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      loop:
        - alt-tab
        - aws-vault
        - firefox
        - inkscape
        - iterm2
        - meld
        - postman
        - rectangle
        - redquits
