- hosts: all

  tasks:

    - name: Install homebrew packages
      homebrew:
        name: "{{ item }}"
      loop:
        - colordiff
        - coreutils
        - docker-credential-helper-ecr
        - entr
        - fd
        - gnu-sed
        - gnu-tar
        - go
        - grep
        - htop
        - jq
        - moreutils
        - neovim
        - node
        - oath-toolkit
        - rename
        - shellcheck
        - terraform-docs
        - tmux
        - tree

    - name: Install homebrew casks
      homebrew_cask:
        name: "{{ item }}"
      loop:
        - alt-tab
        - aws-vault
        - docker
        - firefox
        - inkscape
        - postman
        - rectangle

# vim: syntax=ansible
