- name: Play to install Brew packages
  hosts: all

  tasks:

    - name: Install homebrew packages
      community.general.packaging.os.homebrew:
        name: "{{ item }}"
      loop:
        - bat
        - colima
        - colordiff
        - coreutils
        - docker
        - docker-credential-helper-ecr
        - entr
        - fd
        - gh
        - gnu-sed
        - gnu-tar
        - gpg
        - grep
        - htop
        - jo
        - jq
        - moreutils
        - neovim
        - oath-toolkit
        - rename
        - ripgrep
        - shellcheck
        - terraform-docs
        - tmux
        - tree

    - name: Install homebrew casks
      community.general.packaging.os.homebrew_cask:
        name: "{{ item }}"
      loop:
        - alt-tab
        - aws-vault
        - firefox
        - inkscape
        - meld
        - postman
        - rectangle
