- hosts: all
  tasks:


    - name: Ensure directory for BASH completions
      file:
        path: "{{ target_directory }}/.zsh/bash_completions.d/"
        state: directory


    - name: Ensure directory for ZSH completions
      file:
        path: "{{ target_directory }}/.zsh/completions.d/"
        state: directory

# vim: syntax=ansible
