- name: Play to install ZSH completions
  hosts: all

  vars:
    zsh_completion_directory: "{{ target_directory }}/.config/zsh/completions.d"

  tasks:


    - name: Ensure directory for ZSH completions
      file:
        path: "{{ zsh_completion_directory }}"
        state: directory
        mode: 0755

    - name: Install ZSH completions
      get_url:
        url: "{{ item }}"
        dest: "{{ zsh_completion_directory }}/{{ item.split('/') | last }}"
        mode: 0644
      with_items:
        - https://raw.githubusercontent.com/BurntSushi/ripgrep/master/complete/_rg
        - https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker
        - https://raw.githubusercontent.com/docker/compose/1.29.2/contrib/completion/zsh/_docker-compose
        - https://raw.githubusercontent.com/esc/conda-zsh-completion/master/_conda
        - https://raw.githubusercontent.com/hashicorp/packer/master/contrib/zsh-completion/_packer
        - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/pip/_pip
        - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/taskwarrior/_task
        - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/vault/_vault
        - https://raw.githubusercontent.com/sharkdp/fd/master/contrib/completion/_fd
        - https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_httpie
        - https://raw.githubusercontent.com/zsh-users/zsh/master/Completion/Unix/Command/_ansible
        - https://raw.githubusercontent.com/zsh-users/zsh/master/Completion/Unix/Command/_gem
        - https://raw.githubusercontent.com/zsh-users/zsh/master/Completion/Unix/Command/_jq

    - name: Install ZSH completions with rename
      get_url:
        url: "{{ item.url }}"
        dest: "{{ zsh_completion_directory }}/{{ item.name }}"
        mode: 0644
      with_items:
        - url: https://raw.githubusercontent.com/github/hub/master/etc/hub.zsh_completion
          name: _hub
