- hosts: all
  tasks:


    - name: Install Tmux plugin manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ target_directory }}/.tmux/plugins/tpm"
        update: no


    - name: Install Vim plugin manager
      git:
        repo: https://github.com/gmarik/Vundle.vim.git
        dest: "{{ target_directory }}/.vim/bundle/vundle"
        update: no


    - name: Ensure directory for ZSH plugins
      file:
        path: "{{ target_directory }}/.zsh/plugins"
        state: directory


    - name: Install ZSH base16 plugin
      git:
        repo: https://github.com/chriskempson/base16-shell
        dest: "{{ target_directory }}/.zsh/plugins/base16-shell"
        update: no
      register: base16
    - name: Patch base16 plugin
      patch:
        src: "{{ playbook_dir }}/../patches/base16-shell"
        basedir: "{{ target_directory }}/.zsh/plugins/base16-shell"
      when: base16.changed


    - name: Install ZSH syntax highlighting plugin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: "{{ target_directory }}/.zsh/plugins/zsh-syntax-highlighting"
        update: no


    - name: Install ZSH git prompt plugin
      git:
        repo: https://github.com/olivierverdier/zsh-git-prompt
        dest: "{{ target_directory }}/.zsh/plugins/zsh-git-prompt"
        update: no
      register: git_prompt_plugin
    - name: Fix naming in ZSH git prompt plugin
      copy:
        src: "{{ target_directory }}/.zsh/plugins/zsh-git-prompt/zshrc.sh"
        dest: "{{ target_directory }}/.zsh/plugins/zsh-git-prompt/zsh-git-prompt.plugin.zsh"
      when: git_prompt_plugin.changed


    - name: Install ZSH pip plugin
      get_url:
        url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/plugins/pip/pip.plugin.zsh
        dest: "{{ target_directory }}/.zsh/plugins/"
