- hosts: all

  vars:
    zsh_plugin_directory: "{{ target_directory }}/.config/zsh/plugins"

  tasks:


    - name: Install Tmux plugin manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ target_directory }}/.tmux/plugins/tpm"
        update: no


    - name: Ensure directory for Vim plugin manager
      file:
        path: "{{ target_directory }}/.vim/autoload"
        state: directory
    - name: Install Vim plugin manager
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ target_directory }}/.vim/autoload/plug.vim"
    - name: Install Vim plugins
      shell: |
        vim -c 'PlugUpdate' -c 'qall'
      args:
        creates: "{{ target_directory }}/.vim/plugged/"
      when: target_directory == lookup('env', 'HOME')

    - name: Ensure directory for ZSH plugins
      file:
        path: "{{ zsh_plugin_directory }}"
        state: directory


    - name: Install ZSH base16 plugin
      git:
        repo: https://github.com/chriskempson/base16-shell
        dest: "{{ zsh_plugin_directory }}/base16-shell"
        update: no
      register: base16
    - name: Patch base16 plugin
      patch:
        src: "{{ playbook_dir }}/../patches/base16-shell"
        basedir: "{{ zsh_plugin_directory }}/base16-shell"
      when: base16.changed


    - name: Install ZSH autosuggestions plugin
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "{{ zsh_plugin_directory }}/zsh-autosuggestions"


    - name: Install ZSH fzf plugin
      get_url:
        url: https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh
        dest: "{{ zsh_plugin_directory }}/fzf.plugin.zsh"


    - name: Install ZSH git prompt plugin
      git:
        repo: https://github.com/zsh-git-prompt/zsh-git-prompt
        dest: "{{ zsh_plugin_directory }}/zsh-git-prompt"
        update: no
      register: git_prompt_plugin
    - name: Create link with right naming for ZSH git prompt plugin
      file:
        src: "{{ zsh_plugin_directory }}/zsh-git-prompt/zshrc.sh"
        dest: "{{ zsh_plugin_directory }}/zsh-git-prompt/zsh-git-prompt.plugin.zsh"
        state: link


    - name: Install ZSH per directory history plugin
      get_url:
        url: https://raw.githubusercontent.com/jimhester/per-directory-history/master/per-directory-history.zsh
        dest: "{{ zsh_plugin_directory }}/per-directory-history.plugin.zsh"


    - name: Install ZSH syntax highlighting plugin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: "{{ zsh_plugin_directory }}/zsh-syntax-highlighting"
        update: no


    - name: Install ZSH system clipboard plugin
      git:
        repo: https://github.com/kutsan/zsh-system-clipboard.git
        dest: "{{ zsh_plugin_directory }}/zsh-system-clipboard"
        update: no

# vim: syntax=ansible
