- hosts: all
  become: true
  tasks:

    - name: Ensure useful packages are installed
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - amazon-ecr-credential-helper
        - asunder  # cd ripper
        - audacity  # audio editor
        - autofs
        - baobab  # to analyze disk usage from Thunar context menu
        - boxes
        - entr  # do stuff when files change
        - fd-find
        - feh
        - geary
        - gimp
        - git
        - gnome-font-viewer
        - gparted
        - htop
        - inkscape
        - jo
        - jq
        - lame
        - libreoffice
        - lolcat
        - meld
        - moreutils  # contains sponge command
        - neovim
        - oathtool
        - parcellite  # keeps copied text in the clipboard even after applications have been closed
        - pdfchain
        - pinta
        - pulseaudio-module-bluetooth  # enable bluetooth (fixes Connection Failed: blueman.bluez.errors.DBusFailedError: Protocol not available...)
        - python-is-python3
        - python3-dev
        - python3-venv
        - ranger
        - rename
        - ripgrep
        - shellcheck
        - taskwarrior
        - texlive
        - texlive-lang-german
        - tmux  # use 'CTRL-B' + 'I' to install the plugins
        - trash-cli
        - tree
        - usb-creator-gtk
        - vlc
        - xbacklight
        - xclip
        - xfce4-terminal
        - zsh

    - name: Ensure useless/unwanted packages are removed
      apt:
        state: absent
        name: "{{ item }}"
      loop:
        - gnome-mines
        - gnome-sudoku
        - indicator-messages
        - mousepad
        - parole
        - pidgin
        - ristretto
        - snapd

    - name: Make ZSH default shell
      user:
        name: sebastian
        shell: /bin/zsh

# vim: ft=ansible.yml
