- hosts: all

  tasks:

    - name: Ensure .opt directory
      file:
        path: "{{ target_directory }}/.opt"
        state: directory


    - name: Install Virtualenv
      shell: |
        curl https://pypi.org/project/virtualenv/ | {{ target_directory }}/.bin/pup 'a[href]:contains("tar.gz") attr{href}' | xargs -L 1 wget && \
        tar --extract --strip-components 1 --file *.tar.gz && \
        python3 virtualenv.py {{ target_directory }}/.opt/virtualenv && \
        {{ target_directory }}/.opt/virtualenv/bin/pip install virtualenv
      args:
        chdir: /tmp/
        creates: "{{ target_directory }}/.opt/virtualenv"
        warn: false
    - name: Add link to .bin
      file:
        dest: "{{ target_directory }}/.bin/virtualenv"
        src: "{{ target_directory }}/.opt/virtualenv/bin/virtualenv"
        state: link

# vim: syntax=ansible
