- name: Play to install NPM packages
  hosts: all

  tasks:

    - name: Install npm packages
      community.general.npm:
        name: "{{ item }}"
        global: yes
      loop:
        - eslint_d
        - fixjson
        - jsonlint
        - markdownlint-cli
        - serverless
        - stylelint
        - stylelint-config-standard
        - typescript
        - typescript-language-server
