- hosts: all

  vars:
    packages:
      - {package_name: awscli, executable_name: aws}
      - {package_name: docker-compose, executable_name: docker-compose}
      - {package_name: grip, executable_name: grip}
      - {package_name: httpie, executable_name: http}
      - {package_name: vulture, executable_name: vulture}

  tasks:

    - name: Ensure .opt directory
      file:
        path: "{{ target_directory }}/.opt"
        state: directory


    - name: Install Virtualenv
      shell: |
        curl https://pypi.org/project/virtualenv/ | {{ target_directory }}/.bin/pup 'a[href]:contains("tar.gz") attr{href}' | xargs -L 1 wget && \
        tar --extract --strip-components 1 --file *.tar.gz && \
        python3 virtualenv.py {{ target_directory }}/.opt/virtualenv && \
        {{ target_directory }}/.opt/virtualenv/bin/pip install virtualenv
      args:
        chdir: /tmp/
        creates: "{{ target_directory }}/.opt/virtualenv"
        warn: false
    - name: Add link in .bin
      file:
        dest: "{{ target_directory }}/.bin/virtualenv"
        src: "{{ target_directory }}/.opt/virtualenv/bin/virtualenv"
        state: link

    - name: Install Python utils
      shell: |
        {{ target_directory }}/.bin/virtualenv {{ target_directory }}/.opt/{{ item.package_name }} && \
        {{ target_directory }}/.opt/{{ item.package_name }}/bin/pip install {{ item.package_name }}
      args:
        creates: "{{ target_directory }}/.opt/{{ item.package_name }}"
      with_items: "{{ packages }}"
    - name: Add link in .bin
      file:
        dest: "{{ target_directory }}/.bin/{{ item.executable_name }}"
        src: "{{ target_directory }}/.opt/{{ item.package_name }}/bin/{{ item.executable_name }}"
        state: link
      with_items: "{{ packages }}"

    - name: Install aws completions part one
      file:
        dest: "{{ target_directory }}/.bin/aws_completer"
        src: "{{ target_directory }}/.opt/awscli/bin/aws_completer"
        state: link
    - name: Install aws completions part two
      file:
        dest: "{{ target_directory }}/.zsh/bash_completions.d/aws_zsh_completer.sh"
        src: "{{ target_directory }}/.opt/awscli/bin/aws_zsh_completer.sh"
        state: link

# vim: syntax=ansible
