- hosts: all

  vars:
    bash_completion_directory: "{{ target_directory }}/.config/zsh/bash_completions.d"
    packages:
      ansible:
        links:
          ansible-lint: ansible-lint
          ansible: ansible
      httpie:
        links:
          httpie: http
      aws:
      docker-compose:
      grip:
      pre-commit:
      pylsp:
      sam:
      systemdlint:
      tldr:
      vim-vint:
        links:
          vint: vint
      yamllint:


  tasks:

    - name: Ensure .opt directory
      file:
        path: "{{ target_directory }}/.opt"
        state: directory
        mode: 0755

    - include_tasks: includes/python-util.yml
      loop: "{{ packages | dict2items }}"
      loop_control:
        loop_var: package

    - name: Ensure directory for Bash completions
      file:
        path: "{{ bash_completion_directory }}"
        state: directory
        mode: 0755

    - name: Install aws completions part one
      file:
        dest: "{{ target_directory }}/.bin/aws_completer"
        src: "{{ target_directory }}/.opt/aws/bin/aws_completer"
        state: link
    - name: Install aws completions part two
      file:
        dest: "{{ bash_completion_directory }}/aws_zsh_completer.sh"
        src: "{{ target_directory }}/.opt/aws/bin/aws_zsh_completer.sh"
        state: link

# vim: ft=ansible.yml
