- name: Play to install NPM packages
  hosts: all

  tasks:

    - name: Install npm packages
      community.general.npm:
        name: "{{ item }}"
        global: yes
      loop:
        - aws-cdk
        - cdktf-cli
        - eslint
        - fixjson
        - jsonlint
        - markdownlint-cli
        - prettier
        - serverless
        - stylelint
        - stylelint-config-standard
        - tree-sitter-cli
        - typescript
        - typescript-language-server
        - vscode-langservers-extracted
