- hosts: all

  vars:
    bash_completion_directory: "{{ target_directory }}/.config/zsh/bash_completions.d"
    packages:
      -
        package_name: aws-console
        executable_name: aws-console
        install_url: git+https://github.com/sblask/aws-console.git
      -
        package_name: aws-sam-cli
        executable_name: sam
      -
        package_name: awscli
        executable_name: aws
      -
        package_name: docker-compose
        executable_name: docker-compose
      -
        package_name: grip
        executable_name: grip
      -
        package_name: httpie
        executable_name: http
      -
        package_name: tldr
        executable_name: tldr
      -
        package_name: pre-commit
        executable_name: pre-commit
      -
        package_name: unimatrix
        executable_name: unimatrix
        install_url: git+https://github.com/will8211/unimatrix.git
      -
        package_name: vulture
        executable_name: vulture
      -
        package_name: yamllint
        executable_name: yamllint
      -
        package_name: youtube-dl
        executable_name: youtube-dl

  tasks:

    - name: Ensure .opt directory
      file:
        path: "{{ target_directory }}/.opt"
        state: directory


    - name: Install Python utils
      shell: |
        python3 -m venv {{ target_directory }}/.opt/{{ item.package_name }} && \
        {{ target_directory }}/.opt/{{ item.package_name }}/bin/pip install -U pip && \
        {{ target_directory }}/.opt/{{ item.package_name }}/bin/pip install {{ item.get("install_url", item.package_name) }}
      args:
        creates: "{{ target_directory }}/.opt/{{ item.package_name }}"
      with_items: "{{ packages }}"
    - name: Add link in .bin
      file:
        dest: "{{ target_directory }}/.bin/{{ item.executable_name }}"
        src: "{{ target_directory }}/.opt/{{ item.package_name }}/bin/{{ item.executable_name }}"
        state: link
      with_items: "{{ packages }}"

    - name: Ensure directory for Bash completions
      file:
        path: "{{ bash_completion_directory }}"
        state: directory

    - name: Install aws completions part one
      file:
        dest: "{{ target_directory }}/.bin/aws_completer"
        src: "{{ target_directory }}/.opt/awscli/bin/aws_completer"
        state: link
    - name: Install aws completions part two
      file:
        dest: "{{ bash_completion_directory }}/aws_zsh_completer.sh"
        src: "{{ target_directory }}/.opt/awscli/bin/aws_zsh_completer.sh"
        state: link

# vim: syntax=ansible
