- name: Play to install NPM packages
  hosts: all

  tasks:

    - name: Install npm packages
      npm:
        name: "{{ item }}"
        global: yes
      loop:
        - fixjson
        - jsonlint
        - markdownlint-cli
        - serverless
