- hosts: all

  vars:
    packages:
      - {package_name: aws-sam-cli, executable_name: sam}
      - {package_name: awscli, executable_name: aws}
      - {package_name: docker-compose, executable_name: docker-compose}
      - {package_name: grip, executable_name: grip}
      - {package_name: httpie, executable_name: http}
      - {package_name: tldr, executable_name: tldr}
      - {package_name: unimatrix, executable_name: unimatrix, install_url: "git+https://github.com/will8211/unimatrix.git"}
      - {package_name: vulture, executable_name: vulture}

  tasks:

    - name: Ensure .opt directory
      file:
        path: "{{ target_directory }}/.opt"
        state: directory


    - name: Install Virtualenv
      shell: |
        curl https://pypi.org/project/virtualenv/ | {{ target_directory }}/.bin/pup 'a[href]:contains("tar.gz") attr{href}' | xargs -L 1 wget && \
        tar --extract --strip-components 2 --file *.tar.gz && \
        cp virtualenv.py {{ target_directory }}/.bin/virtualenv && \
        cp --recursive virtualenv_support {{ target_directory }}/.bin/
      args:
        chdir: /tmp/
        creates: "{{ target_directory }}/.bin/virtualenv"
        warn: false

    - name: Install Python utils
      shell: |
        {{ target_directory }}/.bin/virtualenv --python python3 {{ target_directory }}/.opt/{{ item.package_name }} && \
        {{ target_directory }}/.opt/{{ item.package_name }}/bin/pip install {{ item.get("install_url", item.package_name) }}
      args:
        creates: "{{ target_directory }}/.opt/{{ item.package_name }}"
      with_items: "{{ packages }}"
    - name: Add link in .bin
      file:
        dest: "{{ target_directory }}/.bin/{{ item.executable_name }}"
        src: "{{ target_directory }}/.opt/{{ item.package_name }}/bin/{{ item.executable_name }}"
        state: link
      with_items: "{{ packages }}"

    - name: Install aws completions part one
      file:
        dest: "{{ target_directory }}/.bin/aws_completer"
        src: "{{ target_directory }}/.opt/awscli/bin/aws_completer"
        state: link
    - name: Install aws completions part two
      file:
        dest: "{{ target_directory }}/.zsh/bash_completions.d/aws_zsh_completer.sh"
        src: "{{ target_directory }}/.opt/awscli/bin/aws_zsh_completer.sh"
        state: link

# vim: syntax=ansible
