name: Ansible Test

on:
  push:
  schedule:
    - cron: 0 0 * * 0  # weekly

jobs:
  ansible-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
      fail-fast: false

    env:
      ASDF_DATA_DIR: /tmp/dotfiles-ansible-test/.asdf
      PLAYBOOK: ./ansible/ansible-test.yml
      TARGET_DIRECTORY: /tmp/dotfiles-ansible-test

    steps:

      - uses: actions/checkout@v4

      - name: Install other dependencies
        run: |
          pip install ansible-core
          ansible-galaxy collection install ansible.posix community.general

      - name: Prepare Ansible test
        run: mkdir "${TARGET_DIRECTORY}"
      - name: Update PATH for ASDF
        run: |
          echo "${TARGET_DIRECTORY}/.bin" >> "$GITHUB_PATH"
          echo "${TARGET_DIRECTORY}/.asdf/shims" >> "$GITHUB_PATH"
      - name: Run Ansible playbook
        run: |
          env
          echo "$PATH"
          python --version
          ansible-playbook --extra-vars "target_directory=${TARGET_DIRECTORY}" "${PLAYBOOK}"
      - name: Run Ansible playbook again
        run: |
          env
          ls /tmp/dotfiles-ansible-test/.bin/asdf
          echo "$PATH"
          python --version
          asdf --version
          /tmp/dotfiles-ansible-test/.asdf/shims/python3 --version
          /tmp/dotfiles-ansible-test/.asdf/shims/python3.11 --version
          ansible-playbook --extra-vars "target_directory=${TARGET_DIRECTORY}" "${PLAYBOOK}" | tee ansible_result
      - name: Check Ansible idempotency
        run: |
          if grep --quiet 'changed=0.*failed=0' ansible_result
          then
            echo 'Idempotence test: pass'
            exit 0
          else
            echo 'Idempotence test: fail'
            exit 1
          fi
