name: Autoupdate pre-commit

on:
  push:
  schedule:
    - cron: 0 0 * * 0  # weekly

jobs:
  pre-commit-autoupdate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: pip install pre-commit
      - run: pre-commit autoupdate
      - run: git diff --exit-code
